#pragma once

#include "CoreMinimal.h"
#include "Stats/Stats.h"

// Declare stat group
DECLARE_STATS_GROUP(TEXT("Voxel"), STATGROUP_Voxel, STATCAT_Advanced);

// Counters
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Active Chunks"), STAT_VoxelActiveChunks, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Pending Chunks"), STAT_VoxelPendingChunks, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Active Macro Tiles"), STAT_VoxelActiveMacroTiles, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Gen Tasks Running"), STAT_VoxelGenTasksRunning, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Mesh Tasks Running"), STAT_VoxelMeshTasksRunning, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Gen Queue Size"), STAT_VoxelGenQueueSize, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Mesh Queue Size"), STAT_VoxelMeshQueueSize, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("Apply Queue Size"), STAT_VoxelApplyQueueSize, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_DWORD_COUNTER_STAT_EXTERN(TEXT("GPU Gen Jobs Pending"), STAT_VoxelGPUGenJobsPending, STATGROUP_Voxel, VOXELCORE_API);

// Cycle counters
DECLARE_CYCLE_STAT_EXTERN(TEXT("World Tick"), STAT_VoxelWorldTick, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Update Chunks"), STAT_VoxelUpdateChunks, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Drain Apply Queue"), STAT_VoxelDrainApplyQueue, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Promote Pendings"), STAT_VoxelPromotePendings, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Generation"), STAT_VoxelGeneration, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Meshing"), STAT_VoxelMeshing, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Greedy Mesh"), STAT_VoxelGreedyMesh, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Binary Greedy Mesh"), STAT_VoxelGreedyBinary, STATGROUP_Voxel, VOXELCORE_API);

DECLARE_CYCLE_STAT_EXTERN(TEXT("Heightfield Mesh"), STAT_VoxelHeightfieldMesh, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Apply To PMC"), STAT_VoxelApplyToPMC, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Snapshot Neighbors"), STAT_VoxelSnapshotNeighbors, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("GPU Meshing"), STAT_VoxelGPUMeshing, STATGROUP_Voxel, VOXELCORE_API);

// Lighting stats
DECLARE_CYCLE_STAT_EXTERN(TEXT("Light Propagate Sky"), STAT_VoxelLightPropagate, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Light Propagate Block"), STAT_VoxelLightPropagateBlock, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Light Remove"), STAT_VoxelLightRemove, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Light Rebuild"), STAT_VoxelLightRebuild, STATGROUP_Voxel, VOXELCORE_API);

// Memory stats
DECLARE_MEMORY_STAT_EXTERN(TEXT("Voxel Data Memory"), STAT_VoxelDataMemory, STATGROUP_Voxel, VOXELCORE_API);
DECLARE_MEMORY_STAT_EXTERN(TEXT("Mesh Buffer Memory"), STAT_VoxelMeshBufferMemory, STATGROUP_Voxel, VOXELCORE_API);